name = "Stratosworn"
author = "Christian Bradley"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38c843b199082a2c322f87a05acfc99bd3850af10f5ae9e7456c62d3076c853e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
