name = "Stratosworn"
author = "Christian Bradley"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bb5d9d5156721124a5a73d8c9ff3957c00aa84d49c1abf87769848c2b40c965"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
