name = "Stratosworn"
author = "Christian Bradley"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f129886a91e66f20c0e4cabba1dd87dd8441d8bfda7d11b2d63c8328a7e50967"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
